import React, { useMemo, useState } from "react";
import {
  linesArray as _linesArray,
  setLinesArray,
  modified,
  polygonsArray,
  setPolygonsArray,
} from "../vertices";
let polygons = [];

const Runcitruncated5Cell = ({
  verticesArray,
  dimensionOfFigure,
  displayEdges,
  displayVertices,
  onWheel,
  onMouseOver,
  onMouseLeave,
  displayFaces
}) => {
  if (!modified) {
    let linesArray = [];
    const edgeLength = 90;
    const test = new Set();

    for (let i = 0; i < verticesArray.length; i++) {
      for (let j = i; j < verticesArray.length; j++) {
        if (i !== j) {
          let length = 0;
          for (let k = 0; k < dimensionOfFigure; k++) {
            length += (verticesArray[j][k] - verticesArray[i][k]) ** 2;
          }
          length = Math.round(length ** (1 / 2));
          test.add(length)
          if (+dimensionOfFigure > 2) {
            if (length === edgeLength || length === edgeLength - 1) {
              linesArray.push([i, j]);
            }
          }
        }
      }
    }
    const amountOfLines = linesArray.length;
    let ids = 0;
    const lines = [];

    for (let i = 0; i < amountOfLines; i++) {
      lines.push(ids);
      ids += 1;
    }
    setLinesArray(linesArray)
  }

  useMemo(() => {
    if (!modified) {

      polygons = [
        [
          9,
          23,
          46,
          55,
          53,
          41
        ],
        [
          8,
          20,
          45,
          54,
          51,
          40
        ],
        [
          5,
          22,
          47,
          58,
          52,
          39
        ],
        [
          4,
          17,
          47,
          58,
          50,
          38
        ],
        [
          1,
          15,
          46,
          55,
          49,
          37
        ],
        [
          0,
          13,
          45,
          54,
          48,
          36
        ],
        [
          14,
          21,
          44,
          59,
          57,
          43
        ],
        [
          12,
          18,
          44,
          59,
          56,
          42
        ],
        [
          3,
          7,
          41,
          53,
          49,
          37
        ],
        [
          2,
          6,
          40,
          51,
          48,
          36
        ],
        [
          25,
          28,
          32,
          26,
          35,
          34
        ],
        [
          24,
          27,
          30,
          26,
          35,
          33
        ],
        [
          1,
          3,
          7,
          9,
          23,
          15
        ],
        [
          0,
          2,
          6,
          8,
          20,
          13
        ],
        [
          24,
          29,
          31,
          25,
          34,
          33
        ],
        [
          4,
          10,
          11,
          5,
          22,
          17
        ],
        [
          27,
          29,
          31,
          28,
          32,
          30
        ],
        [
          16,
          19,
          43,
          57,
          56,
          42
        ],
        [
          12,
          16,
          19,
          14,
          21,
          18
        ],
        [
          10,
          11,
          39,
          52,
          50,
          38
        ],
        [
          0,
          2,
          36
        ],
        [
          0,
          4,
          24
        ],
        [
          1,
          3,
          37
        ],
        [
          1,
          5,
          25
        ],
        [
          2,
          12,
          27
        ],
        [
          3,
          14,
          28
        ],
        [
          4,
          10,
          38
        ],
        [
          5,
          11,
          39
        ],
        [
          6,
          8,
          40
        ],
        [
          6,
          18,
          30
        ],
        [
          7,
          9,
          41
        ],
        [
          7,
          21,
          32
        ],
        [
          8,
          9,
          26
        ],
        [
          10,
          16,
          29
        ],
        [
          11,
          19,
          31
        ],
        [
          12,
          16,
          42
        ],
        [
          13,
          17,
          33
        ],
        [
          13,
          20,
          45
        ],
        [
          14,
          19,
          43
        ],
        [
          15,
          22,
          34
        ],
        [
          15,
          23,
          46
        ],
        [
          17,
          22,
          47
        ],
        [
          18,
          21,
          44
        ],
        [
          20,
          23,
          35
        ],
        [
          24,
          27,
          29
        ],
        [
          25,
          28,
          31
        ],
        [
          26,
          30,
          32
        ],
        [
          33,
          34,
          35
        ],
        [
          36,
          38,
          42
        ],
        [
          37,
          39,
          43
        ],
        [
          40,
          41,
          44
        ],
        [
          45,
          46,
          47
        ],
        [
          48,
          50,
          56
        ],
        [
          48,
          51,
          54
        ],
        [
          49,
          52,
          57
        ],
        [
          49,
          53,
          55
        ],
        [
          50,
          52,
          58
        ],
        [
          51,
          53,
          59
        ],
        [
          54,
          55,
          58
        ],
        [
          56,
          57,
          59
        ],
        [
          0,
          2,
          27,
          24
        ],
        [
          0,
          4,
          17,
          13
        ],
        [
          0,
          4,
          38,
          36
        ],
        [
          0,
          13,
          33,
          24
        ],
        [
          1,
          3,
          28,
          25
        ],
        [
          1,
          5,
          22,
          15
        ],
        [
          1,
          5,
          39,
          37
        ],
        [
          1,
          15,
          34,
          25
        ],
        [
          2,
          6,
          18,
          12
        ],
        [
          2,
          6,
          30,
          27
        ],
        [
          2,
          12,
          42,
          36
        ],
        [
          3,
          7,
          21,
          14
        ],
        [
          3,
          7,
          32,
          28
        ],
        [
          3,
          14,
          43,
          37
        ],
        [
          4,
          10,
          29,
          24
        ],
        [
          4,
          17,
          33,
          24
        ],
        [
          5,
          11,
          31,
          25
        ],
        [
          5,
          22,
          34,
          25
        ],
        [
          6,
          8,
          26,
          30
        ],
        [
          6,
          18,
          44,
          40
        ],
        [
          7,
          9,
          26,
          32
        ],
        [
          7,
          21,
          44,
          41
        ],
        [
          8,
          9,
          23,
          20
        ],
        [
          8,
          9,
          41,
          40
        ],
        [
          8,
          20,
          35,
          26
        ],
        [
          9,
          23,
          35,
          26
        ],
        [
          10,
          11,
          19,
          16
        ],
        [
          10,
          11,
          31,
          29
        ],
        [
          10,
          16,
          42,
          38
        ],
        [
          11,
          19,
          43,
          39
        ],
        [
          12,
          16,
          29,
          27
        ],
        [
          12,
          18,
          30,
          27
        ],
        [
          13,
          17,
          47,
          45
        ],
        [
          13,
          20,
          35,
          33
        ],
        [
          14,
          19,
          31,
          28
        ],
        [
          14,
          21,
          32,
          28
        ],
        [
          15,
          22,
          47,
          46
        ],
        [
          15,
          23,
          35,
          34
        ],
        [
          16,
          19,
          31,
          29
        ],
        [
          17,
          22,
          34,
          33
        ],
        [
          18,
          21,
          32,
          30
        ],
        [
          20,
          23,
          46,
          45
        ],
        [
          36,
          38,
          50,
          48
        ],
        [
          36,
          42,
          56,
          48
        ],
        [
          37,
          39,
          52,
          49
        ],
        [
          37,
          43,
          57,
          49
        ],
        [
          38,
          42,
          56,
          50
        ],
        [
          39,
          43,
          57,
          52
        ],
        [
          40,
          41,
          53,
          51
        ],
        [
          40,
          44,
          59,
          51
        ],
        [
          41,
          44,
          59,
          53
        ],
        [
          45,
          46,
          55,
          54
        ],
        [
          45,
          47,
          58,
          54
        ],
        [
          46,
          47,
          58,
          55
        ],
        [
          48,
          50,
          58,
          54
        ],
        [
          48,
          51,
          59,
          56
        ],
        [
          49,
          52,
          58,
          55
        ],
        [
          49,
          53,
          59,
          57
        ],
        [
          50,
          52,
          57,
          56
        ],
        [
          51,
          53,
          55,
          54
        ]
      ]
      setPolygonsArray(polygons)
    }
  }, [modified])

  return (
    <svg
      width="600"
      height="400"
      className="svg"
      onWheel={onWheel}
      onMouseEnter={onMouseOver}
      onMouseLeave={onMouseLeave}
    >
      {displayEdges &&
        _linesArray.map((id, index) => {
          let vertex1 = 0;
          let vertex2 = 0;

          vertex1 = _linesArray[index][0];
          vertex2 = _linesArray[index][1];
          return (
            <line
              key={id}
              x1="200"
              y1="200"
              x2="400"
              y2="200"
              stroke="white"
              id={`line${id}`}
              className="line"
              vertex1={vertex1}
              vertex2={vertex2}
            />
          );
        })}

      {displayFaces && +dimensionOfFigure >= 2
        ? polygonsArray.map((arr, index) => (
          <polygon
            data-points={JSON.stringify(arr)}
            key={index}
            points="0 0, 0 0, 0 0, 0 0"
            fill={`rgba(255,255, 255, 0.3)`}
            className="polygon"
            data-type={arr.length}
          // onClick={() => {
          //   const newArr = [...testPolygons, arr];
          //   setTestPolygons(newArr)
          //   polygons = polygons.map((el, index2) => index2 !== index ? el : []);
          //   console.clear();
          //   console.log(newArr)
          // }}
          />
        ))
        : null}

      {displayVertices
        ? verticesArray.map((item, index) => (
          <circle
            onClick={() => {
              console.log(verticesArray[index], index);
            }}
            key={index}
            cx="300"
            cy="200"
            r="2"
            fill="white"
            id={`circle${index}`}
            className="circle"
            onContextMenu={(e) => {
              e.preventDefault();
              e.target.style.display = "none";
            }}
          />
        ))
        : null}
    </svg>
  );
};

export default Runcitruncated5Cell;
